name: green_events_2
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_month_picker: ^0.0.1
  intl: ^0.17.0
  timeago: ^3.2.0

  cupertino_icons: ^1.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/logo.png

flutter:
  uses-material-design: true

  assets:
    - lib/assets/media.png
    - lib/assets/background.png
    - lib/assets/logo-no-background 1 (1).png
    - lib/assets/Group 9.png
    - lib/assets/media (2).png
    - lib/assets/media (4).png
    - lib/assets/media (5).png
    - lib/assets/Barcode-PNG-Photo 1.png
    - lib/assets/3d_avatar_18.png
    - lib/assets/Group 1.png
    - lib/assets/visa.png
    - lib/assets/mastercard.png
